### ISSUE TITLE
move dependency installation to Docker image build-time

### ISSUE THREAD

**Issue by xdadwal** [dadwalakshay/the-django-boilerplate#4]
Currently dependencies are being installed while starting up Docker container which causes longer downtime, hence it should be moved to build-time of Docker image to improve start time of Docker container.

**Comment by con-mark** [comment]
I can try this if you don't mind assigning to me :)

**Comment by xdadwal** [comment]
Thanks for showing interest, assigned to you @con-mark 
Please share your PR for review.
